language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="zipperposition:. logtk:. libzipperposition:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="zipperposition" OCAML_VERSION="4.03.0"
  - PACKAGE="zipperposition" OCAML_VERSION="4.04.2"
  - PACKAGE="zipperposition" OCAML_VERSION="4.05.0"
  - PACKAGE="zipperposition" OCAML_VERSION="4.06.0"
